FROM node:20-alpine as build-stage
WORKDIR /usr/src/int20
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate

FROM node:20-alpine as production-stage
COPY --from=build-stage /usr/src/int20 /usr/src/int20
WORKDIR /usr/src/int20
EXPOSE 3000
CMD ["./start.sh"]